# project_name=gicma-horizon
version: "3.4"
services:
  horizon:
    image: gicmadev/horizon
    build: .
    volumes:
      - ./downloads:/downloads
      - ./prod.secret.exs:/app/config/prod.secret.exs
    networks:
      - horizon
    env_file:
      - ./.env.production.local

  nginx:
    image: nginx:1.19
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf
      - ./downloads:/private/downloads
    networks:
      - horizon
      - traefik
    labels:
        traefik.frontend.rule: "Host:warp.horizon.gicma.dev,horizon.gicma.dev"
        traefik.enable: true

networks:
  traefik:
    external: true
  horizon:
    external: true
