# project_name=podcloud
version: "3.4"
services:
  horizon:
    image: "podcloud-horizon"
    build:
      context: .
      target: runner
    volumes:
      - ./.mix:/var/run/.mix
      - ./downloads:/downloads
      - ./tmp:/tmp
      - .:/app
    networks:
      - default
      - podcloud
    ports:
      - 4000
    env_file:
      - ./.env.development.local
    environment:
      MIX_HOME: /var/run/.mix

  nginx:
    image: nginx:1.19
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
      - ./downloads:/private/downloads
    networks:
      - default
      - podcloud
      - traefik
    labels:
      traefik.frontend.rule: "Host:warp-horizon.gicma.dev.test,horizon.gicma.dev.test"
      traefik.frontend.priority: 999999

  webpack:
    image: node:12
    volumes:
      - .:/app
    networks:
      - default
      - podcloud
    working_dir: /app
    labels:
      traefik.enabled: false
    command: ["npm", "run", "watch"]

  # storybook:
  #   image: node:12
  #   volumes:
  #     - .:/app
  #   networks:
  #     - default
  #     - traefik
  #     - podcloud
  #   working_dir: /app
  #   labels:
  #     traefik.frontend.rule: "HostRegexp:sb.horizon.gicma.dev.test"
  #     traefik.frontend.priority: 999999
  #     traefik.port: 6006
  #   command: ["npm", "run", "storybook"]

  fake_s3:
    image: camjackson/fake-s3
    ports:
      - "0.0.0.0:4569:4569"
    networks:
      - traefik
      - podcloud
      - default
    volumes:
      - /fakes3_root

networks:
  podcloud:
    external: true
  traefik:
    external: true
