# project_name=podcloud
version: "3.4"
services:
  horizon:
    image: "podcloud-horizon"
    build:
      context: .
      target: runner
    volumes:
      - ./.mix:/var/run/.mix
      - ./downloads:/downloads
      - .:/app
    networks:
      - traefik
      - podcloud
    ports:
      - 4000:4000
    labels:
        traefik.frontend.rule: "HostRegexp:horizon.{host:podcloud}.test"
        traefik.frontend.priority: 999999
        traefik.port: 4000

  webpack:
    image: node:10
    volumes:
      - .:/app
    networks:
      - podcloud
    working_dir: /app
    labels:
        traefik.enabled: false
    command: ["npm", "run", "watch"]

  storybook:
    image: node:10
    volumes:
      - .:/app
    networks:
      - traefik
      - podcloud
    working_dir: /app
    labels:
        traefik.frontend.rule: "HostRegexp:sb.horizon.podcloud.test"
        traefik.frontend.priority: 999999
        traefik.port: 6006
    command: ["npm", "run", "storybook"]

  fake_s3:
    image: lphoward/fake-s3
    ports:
      - 4569:4569
    networks:
      - traefik
      - podcloud
    volumes:
      - /fakes3_root

networks:
  podcloud:
    external: true
  traefik:
    external: true

volumes:
  mix:
